### PR TITLE
Ch setup api doc using swagger

### PR DESCRIPTION
**Pull request by marusoft**
#### What does this PR do?
* Setup API documentation using swagger
#### Description of Task to be completed?
* Setup TravisCI and Test Coverage(Coveralls) 
* Setup Heroku pipeline CI/CD 
#### How should this be manually tested?
* `git clone https://github.com/fbdevc-opeke-clan/opekeclan-backend.git` 
* `cd opekeclan-backend`
* `git checkout ch-setup-api-doc-using-swagger`
* `npm install`
* `npm run start:dev`
* Visit `http://localhost:3000/api/v1/docs/`
#### Any background context you want to provide?
* N/A
#### What are the relevant trello board?
* [ch-setup-api-doc-using-swagger](https://trello.com/c/QW2pCC7q/)
#### Screenshots or gifs (if appropriate)
Screenshot from 2020-04-25 12-39-17
#### Questions:
* N/A

### CODE REVIEW

**Review by trafiki — APPROVED** [review]
Good job.

**Review by mudathirlawal — APPROVED** [review]
I think you should add "run npm install" as the third step of the guidelines for running manual test. I works fine, though. Good job!

**Comment by marusoft** [comment]
> I think you should add "run npm install" as the third step of the guidelines for running manual test. I works fine, though. Good job!

thanks @mudathirlawal  done already

**Comment by marusoft** [comment]
> Good job.

thanks @trafiki

**Review by kicekream — COMMENTED** [review]
works as described

**Pull request merged**
