### PR TITLE
Ch setup Postgres Database and Tables

### PR DESCRIPTION
**Pull request by Oluwayelu**
**What does this PR do?**

- It implement database and tables creation

**Description of tasks to be completed**

- Setup Heroku pipeline CI/CD

**How should this be manually tested**

- `git clone https://github.com/fbdevc-opeke-clan/opekeclan-backend.git`
- `cd opekeclan-backend`
- `git checkout postgres`
create development and test db
For linux users:
- `createdb opekeclan_backend`
- `createdb opekeclan_backend_test`

For windows users:
- `CREATE DATABASE opekeclan_backend;`
- `CREATE DATABASE opekeclan_backend_test`
create tables
 `npm run migrate`

**What are the relevant trello board?**
[setup-a-postgresql-database](https://trello.com/c/YPWVo5LA/5-setup-a-postgresql-database) 

**Screenshots or gifs (if appropriate)**

opeke1

opeke2

opke4

### CODE REVIEW

**Review by mudathirlawal — CHANGES_REQUESTED** [review]
Hi Oluwayelu!

After creating the database I did not get a notification that the db has been successfully created. Kindly add the necessary code that implements this feature  as discussed. Also add the necessary commands that testers can use to list the databases and tables in the test guidelines so that testers can view the available databases or see the content of the tables.

I think we are doing well, let's move it.

**Review by kicekream — APPROVED** [review]
works as described, nice work sir

**Review by marusoft — APPROVED** [review]
awesome work @Oluwayelu
@Oluwayelu  please change the label to READY TO MERGE

**Review by trafiki — APPROVED** [review]
Good job.

**Comment by mudathirlawal** [comment]
Okay it works

**Review by mudathirlawal — COMMENTED** [review]
Okay

**Review by mudathirlawal — APPROVED** [review]

**Pull request merged**
